set -g default-terminal "screen-256color"
set-option -g default-command "reattach-to-user-namespace -l zsh"

#### OPTIONS

# c-a instead of c-b
unbind C-b
unbind l
set -g prefix C-a
bind-key C-a last-pane
bind-key a send-prefix

bind r source-file ~/.tmux.conf
set -g base-index 1
set -s escape-time 1
set renumber-windows on

# walkabout
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# synchronization
bind e setw synchronize-panes on
bind E setw synchronize-panes off

# Options from Mark Volkmann's config
setw -g aggressive-resize on
setw -g mode-keys vi
setw -g monitor-activity on
set -g visual-activity on

bind | split-window -h # in addition to "
bind - split-window -v # in addition to %

bind r source-file ~/.tmux.conf \; display "reloaded"

set -g status-utf8 on
set -g status-left "[#S:#I.#P]"
setw -g status-right '(%H:%M)'

#### COLOR

# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour245 #brcyan
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour244
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour230 #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour colour64 #green
