set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

unbind ^A
bind ^A select-pane -t :.+

unbind %
bind | split-window -h
bind - split-window -v

# use vim motion to move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim resize keys
bind < resize-pane -L 5
bind > resize-pane -R 5
bind + resize-pane -U 5
bind - resize-pane -D 5
