#!/bin/sh
cd ~/code/sideprojects/continuum
new_session

# editor window
split 1 -h
send_keys 1.0 " tmux select-layout main-vertical" "Enter"
send_keys 1.0 " clear" "Enter"
send_keys 1.1 "vim" "Enter"
tmux rename-window -t 1 editor

# server window
new_window -n server
send_keys 2.0 "./manage.py runserver localhost:8000" "Enter"
