#!/bin/sh
cd ~/code/sideprojects/funding/funding
new_session

# editor window
split 1 -h
send_keys 1.0 " tmux select-layout main-vertical && clear" "Enter"
send_keys 1.0 "git status" "Enter"
send_keys 1.1 "vim" "Enter"
tmux rename-window -t 1 editor

## server window
new_window -n server
send_keys 2.0 "../funding-manage.sh runserver" "Enter"
