#!/bin/sh
cd ~/code/rockfish/salt
new_session

# editor window
split 1 -h
send_keys 1.0 " tmux select-layout main-vertical && clear" "Enter"
send_keys 1.1 "cd srv/salt" "Enter"
send_keys 1.1 "vim" "Enter"
tmux rename-window -t 1 editor
