#!/bin/sh
rm -f .git/tags
/usr/local/bin/ctags --tag-relative -Rf.git/tags --exclude=.git --languages=-javascript,sql 2>/dev/null && echo "Built tags for project"
[[ $VIRTUAL_ENV ]] && /usr/local/bin/ctags --append -Rf.git/tags --languages=-javascript,sql $VIRTUAL_ENV 2>/dev/null && echo "Built tags for environment"
